### ISSUE TITLE
Milestone: Created Kanban board

### ISSUE THREAD

**Issue by geekelo** [geekelo/domins-recipe_app#11]
Link to Kanban [here](https://github.com/users/geekelo/projects/2) for a team of 2:
@Bleu-Yves-Sopoude 
@geekelo

**Comment by zieeco** [comment]
Hi @Team,

<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Fantastic setting up the kanban board for your project 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Nice effort with the Kanban board. ✔️


## Required Changes ♻️
_Check the comments below._

- [ ] Please, kindly add some description to these issues to state what to work on. #10 #1 #2 #3 #4 #5 #6 #7 #8
- [ ] Please, also add some tasks for your models as this is the foundation for building every and any other part of your project.




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @geekelo and @Bleu-Yves-Sopoude,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well-assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly add issues for these two tasks as indicated by the previous reviewer.

  ![image](https://github.com/geekelo/domins-recipe_app/assets/36542986/1ad99073-5013-421a-8ced-71601fc945aa)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TuyishimireEric** [comment]
# Status: APPROVED 🟢  
### Hi  @TEAM 👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉


## Highlight 👍 
✅ Kanban columns are complete 👍 
✅ Made suggested changes 👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
